### PR TITLE
Add `ignore` array support in Coalesce()

### LINKED ISSUE #64: Support `ignore` values for Coalesce()
Add support in Coalesce() to take an optional `ignore` array parameter. If a found key is set to a value in `ignore`, Coalesce() will skip it as though it doesn't exist. Useful for ignoring things like `{"key": ""}`

### PR DESCRIPTION
**Pull request by JoshKCarroll**
Closes #64

### CODE REVIEW

**Comment by JoshKCarroll** [comment]
Actual coverage, for reference:
```
ok      github.com/qntfy/kazaam 0.011s  coverage: 93.2% of statements
ok      github.com/qntfy/kazaam/kazaam  0.009s  coverage: 54.5% of statements
ok      github.com/qntfy/kazaam/transform       0.010s  coverage: 89.9% of statements
```

**Comment by JoshKCarroll** [comment]
Goveralls seems to only be running top level tests and ignoring the ones in `transform/`

**Comment by JoshKCarroll** [comment]
@chilland reviewed

**Comment by JeanMertz** [comment]
Looking at the example, this change means I can't have a source JSON key called `ignore`, and use the coalesce transformation on that key, is that correct?

I don't have that use-case, but I was writing some extra transformations (such as `move`) and was considering how to design the spec API, and took this one as an example, which got me thinking about the fact that the current API design means any extra added spec option name is another name that you can no longer use in the source JSON.

**Pull request merged**
