### PR TITLE
Use jsonparser

### PR DESCRIPTION
**Pull request by JoshKCarroll**
Benchmarks:
image

### CODE REVIEW

**Comment by ryanleary** [comment]
These improvements are tremendous. Two thoughts:
1) We should keep this as a topic branch for now and tag some RC releases and test in production to make sure there aren't any real-world use cases broken that aren't covered in tests
2) We will either need to roll the major version number (due to breaking API changes) or we can do a minor version change and maintain but deprecate the simplejson-based API.

**Comment by JoshKCarroll** [comment]
Thanks @ryanleary, will get it over to an RC branch. From earlier discussion with @chilland I think we want to do a major version rev to v3 once this is finalized (assuming you're good with that) - it ends up being a lot of duplicated code to try to maintain both.

**Comment by ryanleary** [comment]
Fine by me. Let's merge it to a `v3` branch and tag as rc1 then get it integrated for testing.

**Comment by JoshKCarroll** [comment]
Updated to remove required JSON validation, which significantly slowed down all the transforms.

**Pull request merged**
